package service

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/TomasGrbalik/deckhand/internal/domain"
)

// doNotEditHeader is prepended to every generated file in .deckhand/.
const doNotEditHeader = `# Generated by deckhand — DO NOT EDIT
# Source: .deckhand.yaml
# Regenerate with: deckhand up
`

// deckhandDir is the name of the generated output directory.
const deckhandDir = ".deckhand"

// ComposeRunner executes docker compose operations. The infra layer provides
// the real implementation; tests use a fake.
type ComposeRunner interface {
	Up(projectDir, composePath string, build bool) error
	Down(projectDir, composePath string) error
	Destroy(projectDir, composePath string) error
}

// VolumeInfo holds metadata about a discovered Docker volume.
type VolumeInfo struct {
	Name string
}

// VolumeManager lists and removes Docker volumes by label. Used by Destroy
// to clean up named volumes created by deckhand.
type VolumeManager interface {
	ListByProject(projectName string) ([]VolumeInfo, error)
	Remove(volumeName string) error
}

// EnvironmentService orchestrates the full dev container lifecycle.
// CLI commands call Up, Down, and Destroy through this service.
type EnvironmentService struct {
	templates  TemplateSource
	compose    ComposeRunner
	volumes    VolumeManager
	project    domain.Project
	projectDir string
}

// NewEnvironmentService creates an EnvironmentService.
// projectDir is the root directory containing .deckhand.yaml.
// volumes may be nil — if nil, Destroy skips volume cleanup.
func NewEnvironmentService(
	templates TemplateSource,
	compose ComposeRunner,
	volumes VolumeManager,
	project domain.Project,
	projectDir string,
) *EnvironmentService {
	return &EnvironmentService{
		templates:  templates,
		compose:    compose,
		volumes:    volumes,
		project:    project,
		projectDir: projectDir,
	}
}

// Up renders templates, writes them to .deckhand/, and starts containers.
func (s *EnvironmentService) Up(build bool) error {
	tmplSvc := NewTemplateService(s.templates)
	resolved, _ := MergeMounts(domain.Mounts{}, domain.Mounts{}, s.project.Mounts)
	out, err := tmplSvc.Render(s.project, resolved)
	if err != nil {
		return fmt.Errorf("rendering templates: %w", err)
	}

	outDir := filepath.Join(s.projectDir, deckhandDir)
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return fmt.Errorf("creating %s directory: %w", deckhandDir, err)
	}

	dockerfilePath := filepath.Join(outDir, "Dockerfile")
	if err := os.WriteFile(dockerfilePath, []byte(doNotEditHeader+"\n"+out.Dockerfile), 0o600); err != nil {
		return fmt.Errorf("writing Dockerfile: %w", err)
	}

	composePath := filepath.Join(outDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(doNotEditHeader+"\n"+out.Compose), 0o600); err != nil {
		return fmt.Errorf("writing docker-compose.yml: %w", err)
	}

	if err := s.compose.Up(s.projectDir, composePath, build); err != nil {
		return fmt.Errorf("compose up: %w", err)
	}

	return nil
}

// ErrNoEnvironment is returned when Down or Destroy is called without a prior Up.
var ErrNoEnvironment = errors.New("no environment found")

// composePath returns the path to the generated compose file and checks it exists.
func (s *EnvironmentService) composePath() (string, error) {
	p := filepath.Join(s.projectDir, deckhandDir, "docker-compose.yml")
	if _, err := os.Stat(p); err != nil {
		if os.IsNotExist(err) {
			return "", ErrNoEnvironment
		}
		return "", fmt.Errorf("checking compose file: %w", err)
	}
	return p, nil
}

// Down stops containers but leaves the .deckhand/ directory intact.
func (s *EnvironmentService) Down() error {
	composePath, err := s.composePath()
	if err != nil {
		return err
	}
	if err := s.compose.Down(s.projectDir, composePath); err != nil {
		return fmt.Errorf("compose down: %w", err)
	}
	return nil
}

// ProjectVolumes returns the list of deckhand-managed volumes for this project.
// The CLI uses this to display volume names in the destroy confirmation prompt.
// Returns nil if no VolumeManager is configured.
func (s *EnvironmentService) ProjectVolumes() ([]VolumeInfo, error) {
	if s.volumes == nil {
		return nil, nil
	}
	return s.volumes.ListByProject(s.project.Name)
}

// Destroy stops containers, removes labeled volumes, and deletes the
// .deckhand/ directory.
func (s *EnvironmentService) Destroy() error {
	composePath, err := s.composePath()
	if err != nil {
		if errors.Is(err, ErrNoEnvironment) {
			return nil // nothing to destroy
		}
		return err
	}
	if err := s.compose.Destroy(s.projectDir, composePath); err != nil {
		return fmt.Errorf("compose destroy: %w", err)
	}

	// Remove named volumes discovered by label.
	if s.volumes != nil {
		vols, err := s.volumes.ListByProject(s.project.Name)
		if err != nil {
			return fmt.Errorf("listing project volumes: %w", err)
		}
		for _, v := range vols {
			if err := s.volumes.Remove(v.Name); err != nil {
				return fmt.Errorf("removing volume %q: %w", v.Name, err)
			}
		}
	}

	outDir := filepath.Join(s.projectDir, deckhandDir)
	if err := os.RemoveAll(outDir); err != nil {
		return fmt.Errorf("removing %s directory: %w", deckhandDir, err)
	}

	return nil
}
