package service_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/TomasGrbalik/deckhand/internal/domain"
	"github.com/TomasGrbalik/deckhand/internal/service"
)

// spyCompose records calls to ComposeRunner methods.
type spyCompose struct {
	upCalls      []composeCall
	downCalls    []composeCall
	destroyCalls []composeCall
	upErr        error
	downErr      error
	destroyErr   error
}

type composeCall struct {
	projectDir  string
	composePath string
	build       bool // only relevant for Up
}

func (f *spyCompose) Up(projectDir, composePath string, build bool) error {
	f.upCalls = append(f.upCalls, composeCall{projectDir, composePath, build})
	return f.upErr
}

func (f *spyCompose) Down(projectDir, composePath string) error {
	f.downCalls = append(f.downCalls, composeCall{projectDir, composePath, false})
	return f.downErr
}

func (f *spyCompose) Destroy(projectDir, composePath string) error {
	f.destroyCalls = append(f.destroyCalls, composeCall{projectDir, composePath, false})
	return f.destroyErr
}

func newTestEnv(t *testing.T) (*service.EnvironmentService, *spyCompose, string) {
	t.Helper()
	dir := t.TempDir()
	source := newFakeSource()
	compose := &spyCompose{}
	project := domain.Project{
		Name:     "myapp",
		Template: "base",
		Ports:    []domain.PortMapping{{Port: 8080}},
	}
	svc := service.NewEnvironmentService(source, compose, project, dir)
	return svc, compose, dir
}

func TestUp_RendersAndStartsContainers(t *testing.T) {
	svc, compose, dir := newTestEnv(t)

	if err := svc.Up(false); err != nil {
		t.Fatalf("Up() error: %v", err)
	}

	// Verify .deckhand/ directory was created.
	deckhandDir := filepath.Join(dir, ".deckhand")
	info, err := os.Stat(deckhandDir)
	if err != nil {
		t.Fatalf(".deckhand/ not created: %v", err)
	}
	if !info.IsDir() {
		t.Fatal(".deckhand is not a directory")
	}

	// Verify Dockerfile was written with header.
	dockerfile, err := os.ReadFile(filepath.Join(deckhandDir, "Dockerfile"))
	if err != nil {
		t.Fatalf("reading Dockerfile: %v", err)
	}
	if !strings.HasPrefix(string(dockerfile), "# Generated by deckhand — DO NOT EDIT") {
		t.Errorf("Dockerfile missing DO NOT EDIT header\nGot:\n%s", dockerfile)
	}
	if !strings.Contains(string(dockerfile), "Project: myapp") {
		t.Errorf("Dockerfile missing rendered content\nGot:\n%s", dockerfile)
	}

	// Verify docker-compose.yml was written with header.
	composeYAML, err := os.ReadFile(filepath.Join(deckhandDir, "docker-compose.yml"))
	if err != nil {
		t.Fatalf("reading docker-compose.yml: %v", err)
	}
	if !strings.HasPrefix(string(composeYAML), "# Generated by deckhand — DO NOT EDIT") {
		t.Errorf("docker-compose.yml missing DO NOT EDIT header\nGot:\n%s", composeYAML)
	}

	// Verify ComposeRunner.Up was called correctly.
	if len(compose.upCalls) != 1 {
		t.Fatalf("expected 1 Up call, got %d", len(compose.upCalls))
	}
	call := compose.upCalls[0]
	if call.projectDir != dir {
		t.Errorf("Up projectDir = %q, want %q", call.projectDir, dir)
	}
	expectedComposePath := filepath.Join(deckhandDir, "docker-compose.yml")
	if call.composePath != expectedComposePath {
		t.Errorf("Up composePath = %q, want %q", call.composePath, expectedComposePath)
	}
	if call.build {
		t.Error("Up build = true, want false")
	}
}

func TestUp_WithBuildFlag(t *testing.T) {
	svc, compose, _ := newTestEnv(t)

	if err := svc.Up(true); err != nil {
		t.Fatalf("Up() error: %v", err)
	}

	if len(compose.upCalls) != 1 {
		t.Fatalf("expected 1 Up call, got %d", len(compose.upCalls))
	}
	if !compose.upCalls[0].build {
		t.Error("Up build = false, want true")
	}
}

func TestUp_OverwritesPreviousFiles(t *testing.T) {
	svc, _, dir := newTestEnv(t)

	deckhandDir := filepath.Join(dir, ".deckhand")
	if err := os.MkdirAll(deckhandDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(deckhandDir, "Dockerfile"), []byte("stale"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(deckhandDir, "docker-compose.yml"), []byte("stale"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := svc.Up(false); err != nil {
		t.Fatalf("Up() error: %v", err)
	}

	dockerfile, _ := os.ReadFile(filepath.Join(deckhandDir, "Dockerfile"))
	if strings.Contains(string(dockerfile), "stale") {
		t.Error("Dockerfile was not overwritten")
	}
	if !strings.Contains(string(dockerfile), "Project: myapp") {
		t.Error("Dockerfile missing fresh rendered content")
	}
}

func TestUp_DONOTEDITHeaderFormat(t *testing.T) {
	svc, _, dir := newTestEnv(t)

	if err := svc.Up(false); err != nil {
		t.Fatalf("Up() error: %v", err)
	}

	expectedHeader := "# Generated by deckhand — DO NOT EDIT\n# Source: .deckhand.yaml\n# Regenerate with: deckhand up\n"

	for _, name := range []string{"Dockerfile", "docker-compose.yml"} {
		content, err := os.ReadFile(filepath.Join(dir, ".deckhand", name))
		if err != nil {
			t.Fatalf("reading %s: %v", name, err)
		}
		if !strings.HasPrefix(string(content), expectedHeader) {
			t.Errorf("%s has wrong header.\nWant prefix:\n%s\nGot:\n%s", name, expectedHeader, content)
		}
	}
}

func TestDown_StopsContainersKeepsFiles(t *testing.T) {
	svc, compose, dir := newTestEnv(t)

	// First create some files via Up.
	if err := svc.Up(false); err != nil {
		t.Fatalf("Up() error: %v", err)
	}

	if err := svc.Down(); err != nil {
		t.Fatalf("Down() error: %v", err)
	}

	// Verify ComposeRunner.Down was called.
	if len(compose.downCalls) != 1 {
		t.Fatalf("expected 1 Down call, got %d", len(compose.downCalls))
	}
	call := compose.downCalls[0]
	if call.projectDir != dir {
		t.Errorf("Down projectDir = %q, want %q", call.projectDir, dir)
	}

	// Verify .deckhand/ still exists.
	if _, err := os.Stat(filepath.Join(dir, ".deckhand")); err != nil {
		t.Errorf(".deckhand/ should still exist after Down: %v", err)
	}
}

func TestDestroy_RemovesContainersAndFiles(t *testing.T) {
	svc, compose, dir := newTestEnv(t)

	// First create files via Up.
	if err := svc.Up(false); err != nil {
		t.Fatalf("Up() error: %v", err)
	}

	if err := svc.Destroy(); err != nil {
		t.Fatalf("Destroy() error: %v", err)
	}

	// Verify ComposeRunner.Destroy was called.
	if len(compose.destroyCalls) != 1 {
		t.Fatalf("expected 1 Destroy call, got %d", len(compose.destroyCalls))
	}

	// Verify .deckhand/ was removed.
	if _, err := os.Stat(filepath.Join(dir, ".deckhand")); !os.IsNotExist(err) {
		t.Error(".deckhand/ should be removed after Destroy")
	}
}

func TestDestroy_MissingDeckhandDir(t *testing.T) {
	svc, _, _ := newTestEnv(t)

	// .deckhand/ doesn't exist — should not error.
	if err := svc.Destroy(); err != nil {
		t.Fatalf("Destroy() should not error when .deckhand/ is missing: %v", err)
	}
}

func TestUp_TemplateRenderingFails(t *testing.T) {
	dir := t.TempDir()
	source := &fakeSource{err: errors.New("template broken")}
	compose := &spyCompose{}
	project := domain.Project{Name: "myapp", Template: "base"}
	svc := service.NewEnvironmentService(source, compose, project, dir)

	err := svc.Up(false)
	if err == nil {
		t.Fatal("expected error when template rendering fails")
	}
	if !strings.Contains(err.Error(), "template broken") {
		t.Errorf("error should contain cause, got: %v", err)
	}

	// No files should be written.
	if _, statErr := os.Stat(filepath.Join(dir, ".deckhand")); !os.IsNotExist(statErr) {
		t.Error(".deckhand/ should not exist when rendering fails")
	}

	// ComposeRunner should not be called.
	if len(compose.upCalls) != 0 {
		t.Error("ComposeRunner.Up should not be called when rendering fails")
	}
}

func TestUp_ComposeUpFails(t *testing.T) {
	dir := t.TempDir()
	source := newFakeSource()
	compose := &spyCompose{upErr: errors.New("compose failed")}
	project := domain.Project{Name: "myapp", Template: "base"}
	svc := service.NewEnvironmentService(source, compose, project, dir)

	err := svc.Up(false)
	if err == nil {
		t.Fatal("expected error when compose up fails")
	}
	if !strings.Contains(err.Error(), "compose failed") {
		t.Errorf("error should contain cause, got: %v", err)
	}

	// Files should remain (no cleanup on failure).
	if _, statErr := os.Stat(filepath.Join(dir, ".deckhand", "Dockerfile")); statErr != nil {
		t.Error("Dockerfile should remain after compose failure")
	}
}
