package service

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/TomasGrbalik/deckhand/internal/domain"
)

// doNotEditHeader is prepended to every generated file in .deckhand/.
const doNotEditHeader = `# Generated by deckhand — DO NOT EDIT
# Source: .deckhand.yaml
# Regenerate with: deckhand up
`

// deckhandDir is the name of the generated output directory.
const deckhandDir = ".deckhand"

// ComposeRunner executes docker compose operations. The infra layer provides
// the real implementation; tests use a fake.
type ComposeRunner interface {
	Up(projectDir, composePath string, build bool) error
	Down(projectDir, composePath string) error
	Destroy(projectDir, composePath string) error
}

// VolumeInfo holds metadata about a discovered Docker volume.
type VolumeInfo struct {
	Name string
	Size int64 // size in bytes, -1 if unknown
}

// VolumeManager lists and removes Docker volumes by label. Used by Destroy
// to clean up named volumes created by deckhand.
type VolumeManager interface {
	ListByProject(projectName string) ([]VolumeInfo, error)
	Remove(volumeName string) error
}

// NetworkChecker verifies that a Docker network exists.
type NetworkChecker interface {
	NetworkExists(name string) (bool, error)
}

// EnvironmentService orchestrates the full dev container lifecycle.
// CLI commands call Up, Down, and Destroy through this service.
type EnvironmentService struct {
	templates        TemplateSource
	compose          ComposeRunner
	volumes          VolumeManager
	networkChecker   NetworkChecker
	networkStatePath string
	project          domain.Project
	globalConfig     domain.GlobalConfig
	projectDir       string
	logger           func(format string, args ...any)
}

// NewEnvironmentService creates an EnvironmentService.
// projectDir is the root directory containing .deckhand.yaml.
// volumes may be nil — if nil, Destroy skips volume cleanup.
func NewEnvironmentService(
	templates TemplateSource,
	compose ComposeRunner,
	volumes VolumeManager,
	globalConfig domain.GlobalConfig,
	project domain.Project,
	projectDir string,
) *EnvironmentService {
	return &EnvironmentService{
		templates:    templates,
		compose:      compose,
		volumes:      volumes,
		globalConfig: globalConfig,
		project:      project,
		projectDir:   projectDir,
	}
}

// SetLogger configures a function used to log warnings (e.g., skipped mounts).
// If not set, warnings are silently discarded.
func (s *EnvironmentService) SetLogger(fn func(format string, args ...any)) {
	s.logger = fn
}

// SetNetworkSupport configures Docker network checking and IP state
// management. checker may be nil (e.g., for destroy which doesn't need
// to verify the network). statePath is the path to network-state.yaml.
func (s *EnvironmentService) SetNetworkSupport(checker NetworkChecker, statePath string) {
	s.networkChecker = checker
	s.networkStatePath = statePath
}

func (s *EnvironmentService) logf(format string, args ...any) {
	if s.logger != nil {
		s.logger(format, args...)
	}
}

// Up renders templates, writes them to .deckhand/, and starts containers.
// It loads template metadata to extract default mounts, then merges
// template → global → project mounts before rendering.
func (s *EnvironmentService) Up(build bool) error {
	tmplSvc := NewTemplateService(s.templates, NewCompanionRegistry())

	// Load template metadata to get default mounts (e.g., workspace volume).
	templateName := s.project.Template
	if templateName == "" {
		templateName = "base"
	}
	meta, err := s.templates.LoadMeta(templateName)
	if err != nil {
		return fmt.Errorf("loading template metadata: %w", err)
	}

	templateMounts := domain.Mounts{}
	if meta != nil {
		templateMounts = meta.Mounts
	}

	resolved, warnings := MergeMounts(templateMounts, s.globalConfig.Mounts, s.project.Mounts)
	for _, w := range warnings {
		s.logf("warning: %s", w)
	}

	var renderOpts RenderOpts
	if s.globalConfig.Network.IsConfigured() {
		netOpts, netErr := s.allocateNetwork()
		if netErr != nil {
			return netErr
		}
		renderOpts = netOpts
	}

	out, err := tmplSvc.Render(s.project, resolved, renderOpts)
	if err != nil {
		return fmt.Errorf("rendering templates: %w", err)
	}

	outDir := filepath.Join(s.projectDir, deckhandDir)
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return fmt.Errorf("creating %s directory: %w", deckhandDir, err)
	}

	dockerfilePath := filepath.Join(outDir, "Dockerfile")
	if err := os.WriteFile(dockerfilePath, []byte(doNotEditHeader+"\n"+out.Dockerfile), 0o600); err != nil {
		return fmt.Errorf("writing Dockerfile: %w", err)
	}

	composePath := filepath.Join(outDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(doNotEditHeader+"\n"+out.Compose), 0o600); err != nil {
		return fmt.Errorf("writing docker-compose.yml: %w", err)
	}

	if err := s.compose.Up(s.projectDir, composePath, build); err != nil {
		return fmt.Errorf("compose up: %w", err)
	}

	return nil
}

// allocateNetwork checks that the configured Docker network exists and
// allocates (or reuses) a static IP for this project.
func (s *EnvironmentService) allocateNetwork() (RenderOpts, error) {
	net := s.globalConfig.Network

	if s.networkChecker != nil {
		exists, err := s.networkChecker.NetworkExists(net.Name)
		if err != nil {
			return RenderOpts{}, fmt.Errorf("checking network: %w", err)
		}
		if !exists {
			return RenderOpts{}, fmt.Errorf(
				"network %q does not exist — create it with:\n  docker network create --driver=bridge --subnet=%s --gateway=%s %s",
				net.Name, net.Subnet, net.Gateway, net.Name,
			)
		}
	}

	if s.networkStatePath == "" {
		return RenderOpts{}, errors.New("network state path not configured")
	}

	state, err := LoadNetworkState(s.networkStatePath)
	if err != nil {
		return RenderOpts{}, fmt.Errorf("loading network state: %w", err)
	}

	ip, err := AllocateIP(state, net.Subnet, s.project.Name)
	if err != nil {
		return RenderOpts{}, fmt.Errorf("allocating IP: %w", err)
	}

	if err := SaveNetworkState(s.networkStatePath, state); err != nil {
		return RenderOpts{}, fmt.Errorf("saving network state: %w", err)
	}

	return RenderOpts{NetworkName: net.Name, NetworkIP: ip}, nil
}

// ErrNoEnvironment is returned when Down or Destroy is called without a prior Up.
var ErrNoEnvironment = errors.New("no environment found")

// composePath returns the path to the generated compose file and checks it exists.
func (s *EnvironmentService) composePath() (string, error) {
	p := filepath.Join(s.projectDir, deckhandDir, "docker-compose.yml")
	if _, err := os.Stat(p); err != nil {
		if os.IsNotExist(err) {
			return "", ErrNoEnvironment
		}
		return "", fmt.Errorf("checking compose file: %w", err)
	}
	return p, nil
}

// Down stops containers but leaves the .deckhand/ directory intact.
func (s *EnvironmentService) Down() error {
	composePath, err := s.composePath()
	if err != nil {
		return err
	}
	if err := s.compose.Down(s.projectDir, composePath); err != nil {
		return fmt.Errorf("compose down: %w", err)
	}
	return nil
}

// ProjectVolumes returns the list of deckhand-managed volumes for this project.
// The CLI uses this to display volume names in the destroy confirmation prompt.
// Returns nil if no VolumeManager is configured.
func (s *EnvironmentService) ProjectVolumes() ([]VolumeInfo, error) {
	if s.volumes == nil {
		return nil, nil
	}
	return s.volumes.ListByProject(s.project.Name)
}

// Destroy stops containers, removes labeled volumes, and deletes the
// .deckhand/ directory. If the compose file is missing, volume cleanup
// and directory removal still proceed.
func (s *EnvironmentService) Destroy() error {
	composePath, err := s.composePath()
	if err != nil {
		if !errors.Is(err, ErrNoEnvironment) {
			return err
		}
	} else {
		if err := s.compose.Destroy(s.projectDir, composePath); err != nil {
			return fmt.Errorf("compose destroy: %w", err)
		}
	}

	// Remove named volumes discovered by label.
	if s.volumes != nil {
		vols, err := s.volumes.ListByProject(s.project.Name)
		if err != nil {
			return fmt.Errorf("listing project volumes: %w", err)
		}
		for _, v := range vols {
			if err := s.volumes.Remove(v.Name); err != nil {
				return fmt.Errorf("removing volume %q: %w", v.Name, err)
			}
		}
	}

	// Free IP from network state if configured.
	if s.networkStatePath != "" && s.globalConfig.Network.IsConfigured() {
		state, loadErr := LoadNetworkState(s.networkStatePath)
		if loadErr == nil {
			FreeIP(state, s.project.Name)
			if saveErr := SaveNetworkState(s.networkStatePath, state); saveErr != nil {
				s.logf("warning: failed to save network state: %v", saveErr)
			}
		} else {
			s.logf("warning: failed to load network state: %v", loadErr)
		}
	}

	outDir := filepath.Join(s.projectDir, deckhandDir)
	if err := os.RemoveAll(outDir); err != nil {
		return fmt.Errorf("removing %s directory: %w", deckhandDir, err)
	}

	return nil
}
